### ISSUE TITLE
Review data being injected into the datalake

### ISSUE THREAD

**Issue by jbonnet** [5GZORRO/mda#3]
We need to follow what's specified:

1. raw data
2. signed data

we're currently having a mix of both

**Comment by andreggouveia** [comment]
Also, besides the raw data and the signed data, we need to send the operator ID. Furthermore, the monitoring data (json field) must include the raw data, the resource ID and the referenceID.

**Comment by andreggouveia** [comment]
Concerning the Kafka-python library, Kafka Producer has certain restrictions on the parameters to be sent. For example, the arguments must be of type bytes or serializable to bytes via value_serializer or key_serializer. Due to these impositions, we were unable to send everything in a field value: the monitoring data (raw data), the operatorID, and the hashed Data (already encrypted). Therefore we send in 2 different fields, a key with the date signed and encrypted, and a value with the following data:

```
data = {
    "monitoringData" : {
        "metricName" : "cpu_utilization",
        "metricValue" : "0.453",
        "resourceID" : "X",
        "referenceID" : "Y",
        "timestamp": "the time which the metric was measured"
    },
    "operatorID" : "id_example",
    "businessID" : "business_id_flow",
    "networkID" : "network_slice_id"
}
```
With the producer command as:
`producer.send('topic_test', key=hashDataEncrypted, value=data)`

**Comment by andreggouveia** [comment]
@aviweit what you think about the last comment? It is agreeable for you to receive it in this format?

**Comment by andreggouveia** [comment]
[PoS] The last version, updated today, sends to a Kafka topic the agreed fields: 1. the raw data with an associated operator ID, business ID, and network ID; 2. the encrypted data. We will close this issue but we still need to address where the MDA obtains the secret or pair keys to encrypt and finally how DL will decrypt the data send via Kafka producer.
